version: "3.3"
services:
  api:
    build:
      context: .
      dockerfile: backend.Dockerfile
      args:
        env: local
    environment:
      SEED_DATABASE: enabled
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      DB_URL: mongodb://webpage-user:dkjJd8hbJdk81hCkf731@mongodb:27017/webpage
      REDIS_URL: redis://redis:6379/0
      PGP_FINGERPRINT: "68C8 A1DC 2304 CD40 7062 04CC 56A1 80A9 6E52 9E96"
    ports:
      - 3000:3000
    depends_on:
      - redis
      - mongodb
    links:
      - redis
      - mongodb

  redis:
    image: redis
    volumes:
      - ./volumes/redis:/data
    command: redis-server --requirepass dk3Jd83jgd8dj48dAb --appendonly yes
    ports:
      - "6380:6379"

  mongodb:
    image: mongo
    volumes:
      - ./volumes/mongo:/data/db
      - ./api/src/migrations/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin-user
      MONGO_INITDB_ROOT_PASSWORD: dk48d1JdkvnDK38zjnDK1jvkla
      MONGO_INITDB_DATABASE: admin
    ports:
      - "27018:27017"
